apiVersion: v1
kind: Service
metadata:
  name: ${JOB_NAME}-svc
spec:
  type: ClusterIP
  selector:
    app: ${JOB_NAME}
  ports:
    - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${JOB_NAME}
  name: ${JOB_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${JOB_NAME}
  template:
    metadata:
      labels:
        app: ${JOB_NAME}
    spec:
      containers:
        - image: vactory/php-fpm-nginx:1.0.1
          name: ${JOB_NAME}
          ports:
            - containerPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${JOB_NAME}-http
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-redirectscheme@kubernetescrd
spec:
  rules:
    - host: ${SUB_DOMAIN}.k8s.lapreprod.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${JOB_NAME}-svc
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${JOB_NAME}-https
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: le
spec:
  rules:
    - host: ${SUB_DOMAIN}.k8s.lapreprod.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${JOB_NAME}-svc
                port:
                  number: 80
